// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScrGauge_screen_init(void)
{
    ui_ScrGauge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrGauge, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);


}
