// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScrSwitch_screen_init(void)
{
    ui_ScrSwitch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrSwitch, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchButton1 = ui_SwitchButton_create(ui_ScrSwitch);
    lv_obj_set_x(ui_SwitchButton1, -190);
    lv_obj_set_y(ui_SwitchButton1, -50);




    ui_SwitchButton2 = ui_SwitchButton_create(ui_ScrSwitch);
    lv_obj_set_x(ui_SwitchButton2, -110);
    lv_obj_set_y(ui_SwitchButton2, -50);




    ui_SwitchButton3 = ui_SwitchButton_create(ui_ScrSwitch);
    lv_obj_set_x(ui_SwitchButton3, -30);
    lv_obj_set_y(ui_SwitchButton3, -50);




    ui_SwitchButton4 = ui_SwitchButton_create(ui_ScrSwitch);
    lv_obj_set_x(ui_SwitchButton4, 50);
    lv_obj_set_y(ui_SwitchButton4, -50);




    lv_obj_add_event_cb(ui_ScrSwitch, ui_event_ScrSwitch, LV_EVENT_ALL, NULL);

}
