// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScreenGaugeMulti_screen_init(void)
{
    ui_ScreenGaugeMulti = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenGaugeMulti, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenGaugeMulti, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer1 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer1, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer1, -170);
    lv_obj_set_y(ui_LblGaugeMultiPeer1, -140);
    lv_obj_set_align(ui_LblGaugeMultiPeer1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer1, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer1, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer2 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer2, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer2, -50);
    lv_obj_set_y(ui_LblGaugeMultiPeer2, -140);
    lv_obj_set_align(ui_LblGaugeMultiPeer2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer2, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer2, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer3 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer3, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer3, 70);
    lv_obj_set_y(ui_LblGaugeMultiPeer3, -140);
    lv_obj_set_align(ui_LblGaugeMultiPeer3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer3, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer3, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer4 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer4, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer4, -170);
    lv_obj_set_y(ui_LblGaugeMultiPeer4, 20);
    lv_obj_set_align(ui_LblGaugeMultiPeer4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer4, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer4, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer5 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer5, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer5, -50);
    lv_obj_set_y(ui_LblGaugeMultiPeer5, 20);
    lv_obj_set_align(ui_LblGaugeMultiPeer5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer5, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer5, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue1 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue1, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue1, -170);
    lv_obj_set_y(ui_LblGaugeMultiValue1, -20);
    lv_obj_set_align(ui_LblGaugeMultiValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue1, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue1, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue2 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue2, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue2, -50);
    lv_obj_set_y(ui_LblGaugeMultiValue2, -20);
    lv_obj_set_align(ui_LblGaugeMultiValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue2, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue2, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue3 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue3, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue3, 70);
    lv_obj_set_y(ui_LblGaugeMultiValue3, -20);
    lv_obj_set_align(ui_LblGaugeMultiValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue3, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue3, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue4 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue4, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue4, -170);
    lv_obj_set_y(ui_LblGaugeMultiValue4, 140);
    lv_obj_set_align(ui_LblGaugeMultiValue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue4, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue4, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue5 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue5, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue5, -50);
    lv_obj_set_y(ui_LblGaugeMultiValue5, 140);
    lv_obj_set_align(ui_LblGaugeMultiValue5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue5, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue5, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_ScreenGaugeMulti);
    lv_img_set_src(ui_Image1, &ui_img_1844714932);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image1, -170);
    lv_obj_set_y(ui_Image1, -80);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_ScreenGaugeMulti);
    lv_img_set_src(ui_Image2, &ui_img_1844714932);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image2, -50);
    lv_obj_set_y(ui_Image2, -80);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_ScreenGaugeMulti);
    lv_img_set_src(ui_Image4, &ui_img_1844714932);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image4, 70);
    lv_obj_set_y(ui_Image4, -80);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_ScreenGaugeMulti);
    lv_img_set_src(ui_Image5, &ui_img_1844714932);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image5, -170);
    lv_obj_set_y(ui_Image5, 80);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_ScreenGaugeMulti);
    lv_img_set_src(ui_Image6, &ui_img_1844714932);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image6, -50);
    lv_obj_set_y(ui_Image6, 80);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ScreenGaugeMulti, ui_event_ScreenGaugeMulti, LV_EVENT_ALL, NULL);

}
