// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScrSwitch_screen_init(void)
{
    ui_ScrSwitch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrSwitch, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_ScrSwitch);
    lv_img_set_src(ui_Image7, &ui_img_551600910);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image7, -170);
    lv_obj_set_y(ui_Image7, -80);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_ScrSwitch);
    lv_img_set_src(ui_Image8, &ui_img_551600910);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image8, -60);
    lv_obj_set_y(ui_Image8, -80);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_ScrSwitch);
    lv_img_set_src(ui_Image9, &ui_img_551600910);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image9, 50);
    lv_obj_set_y(ui_Image9, -80);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_ScrSwitch);
    lv_img_set_src(ui_Image10, &ui_img_551600910);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image10, 160);
    lv_obj_set_y(ui_Image10, -80);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
